CONFIG_FILE = "enum_config.json"
config = ""

victim_access_key = ""
victim_secret_access_key = ""
victim_session_token = ""
victim_region = ""
victim_buckets = ""
victim_aws_account_ID = ""
victim_aws_username = ""

attacker_access_key = ""
attacker_secret_access_key = ""
attacker_region = ""
attacker_IAM_role_name = ""
attacker_S3_role_arn = ""